apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: tap-overview
spec:
  title: TAP Overview
  description: A "Sunny Day" walk through Tanzu Applicaation Platform
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/eduk8s/lab-markdown-sample
  content:
    image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/eduk8s/lab-markdown-sample
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
